<?php

namespace FKSDB\EventPayment\PriceCalculator\PreProcess;

use FKSDB\ORM\ModelEvent;
use FKSDB\ORM\ModelEventParticipant;
use Nette\Application\BadRequestException;

class EventSchedulePrice extends AbstractPreProcess {
    /**
     * @var \ServiceEventParticipant
     */
    private $serviceEventParticipant;

    public function __construct(\ServiceEventParticipant $serviceEventParticipant) {
        $this->serviceEventParticipant = $serviceEventParticipant;
    }

    public function calculate(array $data, ModelEvent $event) {
        $ids = $this->getData($data);
        $schedule = $event->getParameter('schedule');
        foreach ($ids as $id) {
            $participantSchedule = $this->getParticipantSchedule($id);
            if ($participantSchedule) {
                $price = $this->calculateSchedule($participantSchedule, $schedule);
                $this->price['kc'] += $price['kc'];
                $this->price['eur'] += $price['eur'];
            }
        }
    }

    private function getParticipantSchedule($id) {
        $row = $this->serviceEventParticipant->findByPrimary($id);
        $model = ModelEventParticipant::createFromTableRow($row);
        return $model->schedule;
    }

    public function getGridItems(array $data, ModelEvent $event): array {
        $ids = $this->getData($data);
        $items = [];
        $schedule = $event->getParameter('schedule');
        foreach ($ids as $id) {
            $participantSchedule = $this->getParticipantSchedule($id);
            if ($participantSchedule) {
                $price = $this->calculateSchedule($participantSchedule, $schedule);
                $items[] = [
                    'label' => '',
                    'kc' => $price['kc'],
                    'eur' => $price['eur'],
                ];

            }
        }
        return $items;
    }

    private function calculateSchedule($participantSchedule, $schedule) {
        $data = \json_decode($participantSchedule);
        $price = ['eur' => 0, 'kc' => 0];
        foreach ($data as $key => $selectedId) {
            $parallel = $this->findScheduleItem($schedule, $key, $selectedId);
            $price['kc'] += $parallel['price']['kc'];
            $price['eur'] += $parallel['price']['eur'];
        }
        return $price;
    }

    protected function getData(array $data) {
        return $data['event_participants']; // TODO: Change the autogenerated stub
    }

    private function findScheduleItem($schedule, string $key, int $id) {
        foreach ($schedule as $scheduleKey => $item) {
            if ($scheduleKey !== $key) {
                continue;
            }
            foreach ($item['parallels'] as $parallel) {
                if ($parallel['id'] == $id) {
                    return $parallel;
                }
            }
        }
        throw new BadRequestException('Item nenájdený');
    }


}
