<?php

namespace Events\Accommodation;

use Nette\Application\Request;
use Nette\Config\Helpers;
use Nette\DateTime;
use Tester\Assert;

$container = require '../../bootstrap.php';

class AccommodationTest extends AccommodationTestCase {
    protected $lastPersonId;
    protected $dsefAppId;

    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->lastPersonId = $this->createPerson('Paní', 'Bílá III.',
            [
                'email' => 'bila3-acc@hrad.cz',
                'born' => DateTime::from('2000-01-01'),
            ]);
        $this->dsefAppId = $this->insert('event_participant', [
            'person_id' => $this->lastPersonId,
            'event_id' => $this->eventId,
            'status' => 'cancelled',
        ]);
        $this->insert(\FKSDB\ORM\DbNames::TAB_E_DSEF_PARTICIPANT,
            [
                'event_participant_id' => $this->dsefAppId,
                'e_dsef_group_id' => 2,
            ]);
        $this->insert('event_person_accommodation', [
            'person_id' => $this->lastPersonId,
            'event_accommodation_id' => $this->accId,
        ]);
        $loginId = $this->insert('login', ['person_id' => $this->lastPersonId, 'active' => 1]);
        $this->insert(\FKSDB\ORM\DbNames::TAB_GRANT, ['login_id' => $loginId, 'role_id' => 5, 'contest_id' => 1]);
        $this->authenticate($loginId);

    }

    public function testRegistration() {
        $postData = [
            'participant' => [
                'person_id' => $this->lastPersonId,
                'person_id_1' => [
                    '_c_compact' => ' ',
                    'person' => [
                        'other_name' => 'Pani',
                        'family_name' => 'Bílá III.',
                    ],
                    'person_info' => [
                        'email' => 'bila3-acc@hrad.cz',
                        'id_number' => '1231354',
                        'born' => '15. 09. 2014',
                    ],
                    'post_contact_p' => [
                        'address' => [
                            'target' => 'jkljhkjh',
                            'city' => 'jkhlkjh',
                            'postal_code' => '64546',
                            'country_iso' => null,
                        ],
                    ],
                    'person_accommodation' => [
                        'matrix' => json_encode(['2018-06-05' => $this->accId]),
                    ],
                ],
                'e_dsef_group_id' => 2,
                'lunch_count' => 0,
                'message' => '',
            ],
            'privacy' => 'on',
            'c_a_p_t_cha' => 'pqrt',
            'cancelled____terminated' => 'Přihlásit účastníka',
        ];

        $post = Helpers::merge([], array(
            'action' => 'default',
            'lang' => 'cs',
            'contestId' => 1,
            'year' => 1,
            'eventId' => $this->eventId,
            'id' => $this->dsefAppId,
            'do' => 'application-form-form-submit',
        ));
        $query = $this->connection->query('SELECT DATABASE() as db')->fetch();
        echo $query->db;
        $request = new Request('Public:Application', 'POST', $post, $postData);
        $response = $this->fixture->run($request);
        Assert::type('Nette\Application\Responses\RedirectResponse', $response);
        //file_put_contents('./acc_out.html', $response->getSource());
        //Assert::equal('cancelled', $this->connection->fetchColumn('SELECT status FROM event_participant WHERE event_participant_id=?', $this->dsefAppId));
        Assert::equal('0', $this->connection->fetchColumn('SELECT count(*) FROM event_person_accommodation WHERE event_accommodation_id = ? AND person_id=?', $this->accId, $this->lastPersonId));
    }

    public function getAccommodationCapacity() {
        return 3;
    }
}


$testCase = new AccommodationTest($container);
$testCase->run();
