<?php

namespace Events\Accommodation;

use Nette\DateTime;
use Tester\Assert;

$container = require '../../bootstrap.php';

class AccommodationTest extends AccommodationTestCase {
    protected $lastPersonId;

    public function setUp() {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->lastPersonId = $this->createPerson('Paní', 'Bílá II.',
            [
                'email' => 'bila3-acc@hrad.cz',
                'born' => DateTime::from('2000-01-01'),
            ]);
        $this->insert('event_participant', [
            'person_id' => $this->lastPersonId,
            'event_id' => $this->eventId,
            'status' => 'applied',
        ]);
        $this->insert('event_person_accommodation', [
            'person_id' => $this->lastPersonId,
            'event_accommodation_id' => $this->accId,
        ]);



    }

    public function testRegistration() {
        $request = $this->createPostRequest([
            'participant' => [
                'person_id' => $this->lastPersonId,
                'e_dsef_group_id' => 2,
                'lunch_count' => 0,
                'message' => "",
            ],
            'privacy' => "on",
            'c_a_p_t_cha' => "pqrt",
            'appliedcanceled' => "Přihlásit účastníka",
        ]);
        $response = $this->fixture->run($request);
        Assert::type('Nette\Application\Responses\RedirectResponse', $response);

        Assert::equal('2', $this->connection->fetchColumn('SELECT count(*) FROM event_person_accommodation WHERE event_accommodation_id = ?', $this->accId));
    }

    public function getAccommodationCapacity() {
        return 3;
    }
}


$testCase = new AccommodationTest($container);
$testCase->run();
