language: php

addons:
  hosts:
    - db.fykos.local
    - auth.fykos.local

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
jobs:
  allow_failures:
    - php: 7.2
    - php: 7.3
    - php: 7.4

services:
  - mysql

before_install:
  #  - composer self-update
  - echo $'\n[client]\nuser=root' >> ~/.my.cnf

install:
  #  - composer install --no-interaction --prefer-source
  - "sed -e 's/user:/user: root/' app/config/config.local.neon.sample > app/config/config.local.neon"
  - ./i18n/compile.sh

before_script:
  - ./tests/init-database.sh
  - ./tests/clear-database.sh
  - rm -rf temp/* tmp

script:
  - ./tests/run.sh -j 1

after_failure:
  # Vytiskne obsah souborů *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
