language: php

addons:
  hosts:
    - db.fykos.local
    - auth.fykos.local
  mariadb: '10.4'

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - phpenv config-add tests/php.ini
  - composer self-update

install:
  - composer install --no-interaction --prefer-source
  - "sed -e 's/user:/user: root/' app/config/config.local.neon.sample > app/config/config.local.neon"
  - ./i18n/compile.sh

before_script:
  - sudo mysql -e "ALTER USER root@localhost IDENTIFIED VIA mysql_native_password; SET PASSWORD = PASSWORD('');"
  - composer run-script initTestDatabase
  #- composer run-script clearDatabase - already run in test
  #- rm -rf temp/* tmp - already run in test

script:
  - composer run-script test

after_failure:
  # Vytiskne obsah souborů *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
