<?php

namespace FKSDB\Components\Forms\Controls;

use FKS\Application\IJavaScriptCollector;
use Nette\ComponentModel\IComponent;
use Nette\Diagnostics\Debugger;
use Nette\Forms\Controls\BaseControl;
use Nette\Forms\Controls\TextInput;

class PersonAccommodationMatrix extends TextInput {
    const ID = 'person-accommodation-matrix';

    public function __construct() {
        parent::__construct(_('Accommodation'));
        $this->setAttribute('data-id', self::ID);
    }

    public function setAccommodationDefinition($accommodationDef) {
        $this->setAttribute('data-accommodation-def', json_encode($accommodationDef));

    }

    public function setValue($value) {
        Debugger::barDump($value);
        // throw new \Exception();
        return parent::setValue($value); // TODO: Change the autogenerated stub
    }
}
