openapi: 3.1.0
info:
  title: FKSDB api
  summary: GET api for data stored in FKSDB
  version: 0.0.1
jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
servers:
  - url: http://db.fykos.local/api/
paths:
  /events:
    get: { }
  /events/{eventId}:
    get: { }
  /events/{eventId}/teams:
    get: { }
  /events/{eventId}/participants:
    get: { }
  /contests:
    get: { }
  /contests/{contstId}/organizers:
    get: { }
  /contests/{contstId}/years/{year}/stats:
    get: { }
