version: '3'

services:
  app:
    image: ghcr.io/fykosak/fksdb:web
    restart: on-failure:3
    container_name: fksdb
    environment:
      TZ: 'Europe/Prague'
    volumes:
      - ./config.neon:/app/app/config/config.local.neon # nette config
      - ./log:/app/log
      - ./temp:/app/temp
      - ./upload:/app/upload
    user: 1000:1000 # expects the main user as uid:pid

  mariadb:
    image: mariadb:lts
    container_name: fksdb-mariadb
    restart: on-failure:3
    environment:
      TZ: 'Europe/Prague'
      MYSQL_DATABASE: 'fksdb'
      MYSQL_USER: 'fksdb'
      MYSQL_PASSWORD: 'password' # CREATE STRONG CUSTOM PASSWORD
      MYSQL_ROOT_PASSWORD: 'password' # CREATE STRONG CUSTOM PASSWORD
    volumes:
      - ./mariadb_data:/var/lib/mysql # path to dir with database data
