<?php

namespace FKSDB\Components\Forms\Controls\PersonAccommodation;

use FKSDB\Components\React\IReactComponent;
use Nette\Forms\Controls\HiddenField;

class Matrix extends HiddenField implements IReactComponent {
    const RESOLUTION_ID = 'matrix';

    public function __construct() {
        parent::__construct();
        $this->setAttribute('data-react-root', true);
        $this->setAttribute('data-module', $this->getModuleName());
        $this->setAttribute('data-component', $this->getComponentName());
        $this->setAttribute('data-mode', $this->getMode());
    }

    public function getComponentName() {
        return 'accommodation';
    }

    public function getModuleName() {
        return 'events';
    }

    public function getMode() {
        return self::RESOLUTION_ID;
    }

    /**
     * @return string
     */
    public function getData() {
        return null;
    }

    public function setAccommodationDefinition($accommodationDef) {
        $this->setAttribute('data-data', count($accommodationDef) ? json_encode($accommodationDef) : NULL);
    }

    public function setValue($value) {
        return parent::setValue($value); // TODO: Change the autogenerated stub
    }
}
