<?php

namespace FKSDB\Components\Forms\Controls\PersonAccommodation;

use Nette\Forms\Controls\TextInput;

class Matrix extends TextInput {
    const ResolutionId = 'matrix';

    public function __construct() {
        parent::__construct(_('Accommodation'));
        $this->setAttribute('data-react-root', true);
        $this->setAttribute('data-module', 'events');
        $this->setAttribute('data-component', 'accommodation');
        $this->setAttribute('data-mode', null);
    }

    public function setAccommodationDefinition($accommodationDef) {
        $this->setAttribute('data-data', count($accommodationDef) ? json_encode($accommodationDef) : NULL);
    }

    public function setValue($value) {
        return parent::setValue($value); // TODO: Change the autogenerated stub
    }
}
