-- Adminer 3.5.1 MySQL dump

SET NAMES utf8;
SET foreign_key_checks = 0;
SET time_zone = 'SYSTEM';
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP VIEW IF EXISTS `v_contestant`;
CREATE  VIEW `v_contestant` AS select `contestant`.`person_id` AS `person_id`,`contestant`.`ct_id` AS `ct_id`,`contestant`.`contest_id` AS `contest_id`,`contestant`.`year` AS `year`,`contestant`.`school_id` AS `school_id`,`contestant`.`class` AS `class`,`contestant`.`study_year` AS `study_year`,`person`.`family_name` AS `family_name`,`person`.`other_name` AS `other_name`,`person`.`display_name` AS `display_name`,`person`.`gender` AS `gender` from (`contestant` left join `person` on((`contestant`.`person_id` = `person`.`person_id`)));

DROP VIEW IF EXISTS `v_envelope`;
CREATE  VIEW `v_envelope` AS select `p`.`person_id` AS `person_id`,if(isnull(`p`.`display_name`),concat(`p`.`other_name`,' ',`p`.`family_name`),`p`.`display_name`) AS `CeleJmeno`,`a`.`first_row` AS `PrvniRadek`,`a`.`second_row` AS `DruhyRadek`,`a`.`target` AS `TretiRadek`,`a`.`city` AS `Mesto`,`a`.`postal_code` AS `PSC`,if((`r`.`country_iso` = 'SK'),'Slovakia',NULL) AS `Stat` from ((((`person` `p` left join `post_contact` `pcp` on(((`pcp`.`person_id` = `p`.`person_id`) and (`pcp`.`type` = 'P')))) left join `post_contact` `pcd` on(((`pcd`.`person_id` = `p`.`person_id`) and (`pcd`.`type` = 'D')))) left join `address` `a` on((`a`.`address_id` = if((`pcd`.`address_id` is not null),`pcd`.`address_id`,`pcp`.`address_id`)))) left join `region` `r` on((`a`.`region_id` = `r`.`region_id`))) where (`r`.`country_iso` in ('CZ','SK'));

DROP VIEW IF EXISTS `v_envelope_vyfuk2`;
CREATE  VIEW `v_envelope_vyfuk2` AS select `contestant`.`contest_id` AS `contest_id`,`contestant`.`year` AS `year`,`p`.`person_id` AS `person_id`,coalesce(`p`.`display_name`,concat(`p`.`other_name`,' ',`p`.`family_name`)) AS `CeleJmeno`,if(isnull(`pa`.`address_id`),`school`.`name`,`pa`.`first_row`) AS `PrvniRadek`,if(isnull(`pa`.`address_id`),`contestant`.`class`,`pa`.`second_row`) AS `DruhyRadek`,if(isnull(`pa`.`address_id`),`sa`.`target`,`pa`.`target`) AS `TretiRadek`,if(isnull(`pa`.`address_id`),`sa`.`city`,`pa`.`city`) AS `Mesto`,if(isnull(`pa`.`address_id`),`sa`.`postal_code`,`pa`.`postal_code`) AS `PSC`,NULL AS `Stat` from (((((`contestant` left join `person` `p` on((`p`.`person_id` = `contestant`.`person_id`))) left join `school` on((`school`.`school_id` = `contestant`.`school_id`))) left join `address` `sa` on((`school`.`address_id` = `sa`.`address_id`))) left join `post_contact` `pcp` on((`pcp`.`person_id` = `contestant`.`person_id`))) left join `address` `pa` on((`pcp`.`address_id` = `pa`.`address_id`)));

DROP VIEW IF EXISTS `v_results_fykos25`;
CREATE  VIEW `v_results_fykos25` AS select `p`.`person_id` AS `person_id`,`p`.`other_name` AS `other_name`,`p`.`family_name` AS `family_name`,`t`.`series` AS `series`,`ct`.`study_year` AS `study_year`,round(max(if((`t`.`label` = '1'),if((`ct`.`study_year` in (6,7,8,9,1,2)),(2 * `s`.`raw_points`),`s`.`raw_points`),NULL)),0) AS `1`,round(max(if((`t`.`label` = '2'),if((`ct`.`study_year` in (6,7,8,9,1,2)),(2 * `s`.`raw_points`),`s`.`raw_points`),NULL)),0) AS `2`,round(max(if((`t`.`label` = '3'),`s`.`raw_points`,NULL)),0) AS `3`,round(max(if((`t`.`label` = '4'),`s`.`raw_points`,NULL)),0) AS `4`,round(max(if((`t`.`label` = '5'),`s`.`raw_points`,NULL)),0) AS `5`,round(max(if((`t`.`label` = 'P'),`s`.`raw_points`,NULL)),0) AS `P`,round(max(if((`t`.`label` = 'E'),`s`.`raw_points`,NULL)),0) AS `E`,round(max(if((`t`.`label` = 'S'),`s`.`raw_points`,NULL)),0) AS `S`,round(sum(if((`t`.`label` in ('1','2')),if((`ct`.`study_year` in (6,7,8,9,1,2)),(2 * `s`.`raw_points`),`s`.`raw_points`),`s`.`raw_points`)),0) AS `sum` from (((`contestant` `ct` left join `person` `p` on((`p`.`person_id` = `ct`.`person_id`))) left join `task` `t` on(((`t`.`year` = `ct`.`year`) and (`t`.`contest_id` = `ct`.`contest_id`)))) left join `submit` `s` on(((`s`.`task_id` = `t`.`task_id`) and (`s`.`ct_id` = `ct`.`ct_id`)))) where ((`ct`.`year` = 25) and (`ct`.`contest_id` = 1)) group by `p`.`person_id`,`t`.`series`,`p`.`other_name`,`p`.`family_name`,`ct`.`study_year`;

DROP VIEW IF EXISTS `v_results_fykos26`;
CREATE  VIEW `v_results_fykos26` AS select `p`.`person_id` AS `person_id`,`p`.`other_name` AS `other_name`,`p`.`family_name` AS `family_name`,`t`.`series` AS `series`,`ct`.`study_year` AS `study_year`,round(max(if((`t`.`label` = '1'),if((`ct`.`study_year` in (6,7,8,9,1,2)),(2 * `s`.`raw_points`),`s`.`raw_points`),NULL)),0) AS `1`,round(max(if((`t`.`label` = '2'),if((`ct`.`study_year` in (6,7,8,9,1,2)),(2 * `s`.`raw_points`),`s`.`raw_points`),NULL)),0) AS `2`,round(max(if((`t`.`label` = '3'),`s`.`raw_points`,NULL)),0) AS `3`,round(max(if((`t`.`label` = '4'),`s`.`raw_points`,NULL)),0) AS `4`,round(max(if((`t`.`label` = '5'),`s`.`raw_points`,NULL)),0) AS `5`,round(max(if((`t`.`label` = 'P'),`s`.`raw_points`,NULL)),0) AS `P`,round(max(if((`t`.`label` = 'E'),`s`.`raw_points`,NULL)),0) AS `E`,round(max(if((`t`.`label` = 'S'),`s`.`raw_points`,NULL)),0) AS `S`,round(sum(if((`t`.`label` in ('1','2')),if((`ct`.`study_year` in (6,7,8,9,1,2)),(2 * `s`.`raw_points`),`s`.`raw_points`),`s`.`raw_points`)),0) AS `sum` from (((`contestant` `ct` left join `person` `p` on((`p`.`person_id` = `ct`.`person_id`))) left join `task` `t` on((`t`.`year` = 26))) left join `submit` `s` on(((`s`.`task_id` = `t`.`task_id`) and (`s`.`ct_id` = `ct`.`ct_id`)))) where ((`ct`.`year` = 26) and (`ct`.`contest_id` = 1)) group by `p`.`person_id`,`t`.`series`,`p`.`other_name`,`p`.`family_name`,`ct`.`study_year`;

DROP VIEW IF EXISTS `v_task_stats`;
CREATE  VIEW `v_task_stats` AS (select `task`.`task_id` AS `task_id`,`task`.`label` AS `label`,`task`.`name` AS `name`,`task`.`contest_id` AS `contest_id`,`task`.`year` AS `year`,`task`.`series` AS `series`,`task`.`tasknr` AS `tasknr`,`task`.`points` AS `points`,`task`.`submit_mode` AS `submit_mode`,`task`.`submit_start` AS `submit_start`,`task`.`submit_deadline` AS `submit_deadline`,`task`.`correction_mode` AS `correction_mode`,avg(`submit`.`raw_points`) AS `task_avg`,count(`submit`.`raw_points`) AS `task_count` from (`task` left join `submit` on((`submit`.`task_id` = `task`.`task_id`))) group by `task`.`task_id`);

DROP VIEW IF EXISTS `v_vyfuk2_bezadresniki`;
CREATE  VIEW `v_vyfuk2_bezadresniki` AS (select `contestant`.`ct_id` AS `ct_id`,`contestant`.`person_id` AS `person_id`,`contestant`.`school_id` AS `school_id` from (`contestant` left join `post_contact` on((`post_contact`.`person_id` = `contestant`.`person_id`))) where (isnull(`post_contact`.`person_id`) and (`contestant`.`contest_id` = 2) and (`contestant`.`year` = 2)));

DROP VIEW IF EXISTS `v_vyfuk2_bezadresniki_schools`;
CREATE  VIEW `v_vyfuk2_bezadresniki_schools` AS (select `v_vyfuk2_bezadresniki`.`school_id` AS `school_id`,count(`v_vyfuk2_bezadresniki`.`ct_id`) AS `ct_count` from `v_vyfuk2_bezadresniki` group by `v_vyfuk2_bezadresniki`.`school_id`);

DROP VIEW IF EXISTS `v_vyfuk2_envelope`;
CREATE  VIEW `v_vyfuk2_envelope` AS (select `p`.`person_id` AS `person_id`,coalesce(`p`.`display_name`,concat(`p`.`other_name`,' ',`p`.`family_name`)) AS `CeleJmeno`,if(isnull(`pa`.`address_id`),`school`.`name`,`pa`.`first_row`) AS `PrvniRadek`,if(isnull(`pa`.`address_id`),`contestant`.`class`,`pa`.`second_row`) AS `DruhyRadek`,if(isnull(`pa`.`address_id`),`sa`.`target`,`pa`.`target`) AS `TretiRadek`,if(isnull(`pa`.`address_id`),`sa`.`city`,`pa`.`city`) AS `Mesto`,if(isnull(`pa`.`address_id`),concat(left(`sa`.`postal_code`,3),' ',right(`sa`.`postal_code`,2)),concat(left(`pa`.`postal_code`,3),' ',right(`pa`.`postal_code`,2))) AS `PSC`,NULL AS `Stat`,if(isnull(`pa`.`address_id`),`sa`.`address_id`,`pa`.`address_id`) AS `address_id` from (((((`contestant` left join `person` `p` on((`p`.`person_id` = `contestant`.`person_id`))) left join `school` on((`school`.`school_id` = `contestant`.`school_id`))) left join `address` `sa` on((`school`.`address_id` = `sa`.`address_id`))) left join `post_contact` `pcp` on((`pcp`.`person_id` = `contestant`.`person_id`))) left join `address` `pa` on((`pcp`.`address_id` = `pa`.`address_id`))) where ((`contestant`.`contest_id` = 2) and (`contestant`.`year` = 2)) order by `p`.`family_name`);

DROP VIEW IF EXISTS `v_vyfuk2_obalky_skoly`;
CREATE  VIEW `v_vyfuk2_obalky_skoly` AS (select `school`.`school_id` AS `school_id`,`school`.`name` AS `Instituce`,`address`.`first_row` AS `PrvniRadek`,`address`.`second_row` AS `DruhyRadek`,`address`.`target` AS `TretiRadek`,`address`.`city` AS `Mesto`,concat(left(`address`.`postal_code`,3),' ',right(`address`.`postal_code`,2)) AS `PSC`,NULL AS `Stat`,`school`.`address_id` AS `address_id` from ((`v_vyfuk2_bezadresniki_schools` `s` left join `school` on((`s`.`school_id` = `school`.`school_id`))) left join `address` on((`school`.`address_id` = `address`.`address_id`))) where (`s`.`ct_count` > 1) order by `address`.`postal_code`);

DROP VIEW IF EXISTS `v_vyfuk2_skup_skoly`;
CREATE  VIEW `v_vyfuk2_skup_skoly` AS (select `person`.`family_name` AS `family_name`,`person`.`other_name` AS `other_name`,`b`.`person_id` AS `person_id`,`s`.`school_id` AS `school_id` from ((`v_vyfuk2_bezadresniki_schools` `s` left join `v_vyfuk2_bezadresniki` `b` on((`b`.`school_id` = `s`.`school_id`))) left join `person` on((`b`.`person_id` = `person`.`person_id`))) where (`s`.`ct_count` > 1) order by `person`.`family_name`);

-- 2013-08-30 01:13:45
